import { useCallback, useRef, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Companion } from "@/components/nova/Companion";
import { NovaDemoPanel } from "@/components/nova/NovaDemoPanel";
import {
  NovaConversationPanel,
  type NovaConversationHandle,
  type NovaConversationStatus,
} from "@/components/nova/NovaConversationPanel";
import { NovaVoiceControl } from "@/components/nova/NovaVoiceControl";
import { CompanyNovaActions } from "@/components/nova/CompanyNovaActions";
import {
  CompanyQuestionGenerator,
  type CompanyQuestionGeneratorConfig,
} from "@/components/nova/CompanyQuestionGenerator";
import type { CompanyNovaCommand } from "@/lib/nova/company-command";
import { createAssessment } from "@/lib/assessments.functions";
import { useNovaSenses } from "@/hooks/use-nova-senses";
import {
  expressionLabel,
  stateLabel,
} from "@/lib/nova/expression";
import {
  useNovaVoice,
  voiceLabel,
} from "@/lib/nova/nova-voice";
import {
  Mic2,
  Radio,
  Camera,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface GeneratedQuestion {
  id: string;
  type: "text" | "mcq" | "code";
  text: string;
  weight: number;
  keywords: string[];
  maxLength?: number | null;
  choices?: {
    id: string;
    text: string;
  }[];
  correctChoiceId?: string;
  starterCode?: string;
  testCases?: {
    input: string;
    expectedStdout: string;
  }[];
}

export function NovaConsole({
  className,
  companyUserId,
}: {
  className?: string;
  companyUserId: string;
}) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [status, setStatus] =
    useState<NovaConversationStatus>({
      state: "idle",
      expression: "neutral",
      pulse: 0,
    });

  const [listening, setListening] =
    useState(false);

  const [micSupported, setMicSupported] =
    useState(false);

  const [showQuestionGenerator, setShowQuestionGenerator] =
    useState(false);

  const [questionGeneratorConfig, setQuestionGeneratorConfig] =
    useState<CompanyQuestionGeneratorConfig>({});

  const [generatedQuestions, setGeneratedQuestions] =
    useState<GeneratedQuestion[]>([]);

  const [assessmentTitle, setAssessmentTitle] =
    useState("Nova AI Interview Assessment");

  const [publishing, setPublishing] =
    useState(false);

  const conversationRef =
    useRef<NovaConversationHandle>(null);

  const senses = useNovaSenses();
  const { status: visionStatus } = senses;

  const {
    voices: novaVoices,
    active: activeVoice,
    fellBack,
    setVoice,
  } = useNovaVoice();

  const sensing =
    senses.cameraOn || senses.micOn;

  const handleTapToTalk = useCallback(() => {
    conversationRef.current?.toggleMic();
  }, []);

  /**
   * Publish the questions already generated by Nova.
   *
   * IMPORTANT:
   * This does NOT call the AI.
   * It only calls createAssessment().
   */
  const publishGeneratedAssessment =
    useCallback(async (): Promise<string> => {
      if (publishing) {
        return "Publishing is already in progress.";
      }

      if (!companyUserId?.trim()) {
        const message = "Company account could not be identified.";
        toast.error(message);
        return message;
      }

      if (!generatedQuestions.length) {
        const message =
          "No generated questions are ready. Generate the assessment questions first.";
        toast.error(message);
        setShowQuestionGenerator(true);
        return message;
      }

      setPublishing(true);

      try {
        const questions = generatedQuestions
          .filter(
            (question) =>
              typeof question.text === "string" &&
              question.text.trim().length >= 3,
          )
          .map((question) => ({
            type: question.type,
            text: question.text.trim(),
            weight:
              Number.isFinite(question.weight) &&
              question.weight > 0
                ? question.weight
                : 10,
            keywords: Array.isArray(question.keywords)
              ? question.keywords
              : [],
            maxLength: question.maxLength ?? null,
            choices: question.choices,
            correctChoiceId: question.correctChoiceId,
            starterCode: question.starterCode,
            testCases: question.testCases,
          }));

        if (!questions.length) {
          throw new Error(
            "The generated assessment contains no valid questions.",
          );
        }

        const assessment = await createAssessment({
          data: {
            companyUserId: companyUserId.trim(),
            title:
              assessmentTitle.trim() ||
              "Nova AI Interview Assessment",
            questions,
          },
        });

        console.log("NOVA ASSESSMENT PUBLISHED", {
          id: assessment._id,
          code: assessment.code,
          companyUserId: assessment.companyUserId,
          title: assessment.title,
          questionCount: assessment.questions.length,
        });

        // The dashboard uses this exact React Query key.
        await queryClient.invalidateQueries({
          queryKey: ["company-assessments"],
        });

        await queryClient.refetchQueries({
          queryKey: ["company-assessments"],
          type: "all",
        });

        setGeneratedQuestions([]);
        setShowQuestionGenerator(false);

        toast.success(
          `Assessment published successfully. Code: ${assessment.code}`,
        );

        // Take the company user directly to the real assessment list.
        await navigate({
          to: "/dashboard/assessments",
        });

        return `Assessment published successfully. ${questions.length} questions are now in Assessments. Code: ${assessment.code}.`;
      } catch (error) {
        console.error("NOVA ASSESSMENT PUBLISH FAILED", error);

        const message =
          error instanceof Error
            ? error.message
            : "Failed to publish assessment.";

        toast.error(message);
        return `I could not publish the assessment: ${message}`;
      } finally {
        setPublishing(false);
      }
    }, [
      companyUserId,
      generatedQuestions,
      assessmentTitle,
      publishing,
      queryClient,
      navigate,
    ]);

  /**
   * Handle commands coming directly from Nova.
   */
  const handleCompanyCommand =
    useCallback(
      async (command: CompanyNovaCommand): Promise<string | void> => {
        console.log(
          "Nova company command:",
          command,
        );

        if (
          command.type ===
            "generate_questions" ||
          command.type ===
            "create_assessment"
        ) {
          const config: CompanyQuestionGeneratorConfig =
            {
              role: command.role,
              topic: command.topic,
              difficulty:
                command.difficulty,
              count: command.count,
            };

          setQuestionGeneratorConfig(
            config,
          );

          const role =
            command.role?.trim();

          const topic =
            command.topic?.trim();

          if (role && topic) {
            setAssessmentTitle(
              `${role} — ${topic} AI Assessment`,
            );
          } else if (role) {
            setAssessmentTitle(
              `${role} AI Interview Assessment`,
            );
          } else if (topic) {
            setAssessmentTitle(
              `${topic} AI Interview Assessment`,
            );
          } else {
            setAssessmentTitle(
              "Nova AI Interview Assessment",
            );
          }

          setShowQuestionGenerator(true);

          const countText = command.count ?? 5;
          const roleText = command.role?.trim() || "the requested role";
          const topicText = command.topic?.trim() || "the requested topic";

          return `I'm preparing ${countText} ${roleText} questions${
            command.topic ? ` on ${topicText}` : ""
          }. I'll keep them ready for publishing.`;
        }

        /**
         * Publish flow.
         *
         * "publish it"
         *      ↓
         * confirmation
         *
         * "yes, publish it"
         *      ↓
         * actual publishing
         */
        if (
          command.type ===
          "publish_assessment"
        ) {
          if (!generatedQuestions.length) {
            const message =
              "I don't have generated questions ready yet. Ask me to prepare the assessment questions first.";
            toast.error(message);
            setShowQuestionGenerator(true);
            return message;
          }

          if (command.confirmed) {
            return await publishGeneratedAssessment();
          }

          return "Publishing was not confirmed.";
        }

        if (
          command.type ===
          "schedule_interview"
        ) {
          toast.info(
            "Interview scheduling will be connected to the calendar next.",
          );
          return;
        }

        if (
          command.type ===
          "analyze_candidates"
        ) {
          toast.info(
            "Candidate analysis command received.",
          );
          return;
        }

        if (
          command.type ===
          "hiring_analytics"
        ) {
          toast.info(
            "Hiring analytics command received.",
          );
        }
      },
      [
        generatedQuestions,
        publishGeneratedAssessment,
      ],
    );

  /**
   * Handle right-side hiring buttons.
   */
  const handleCompanyAction =
    useCallback(
      (action: {
        type: string;
        label: string;
        description: string;
      }) => {
        if (
          action.type ===
          "generate_questions"
        ) {
          setQuestionGeneratorConfig({});
          setAssessmentTitle(
            "Nova AI Interview Assessment",
          );
          setShowQuestionGenerator(true);
          return;
        }

        if (
          action.type ===
          "create_assessment"
        ) {
          setQuestionGeneratorConfig({});
          setAssessmentTitle(
            "Nova AI Interview Assessment",
          );
          setShowQuestionGenerator(true);
          return;
        }

        console.log(
          "Nova company action:",
          action,
        );
      },
      [],
    );

  /**
   * Store generated questions immediately.
   *
   * This is the important state bridge:
   *
   * Generator → NovaConsole → Publish
   */
  const handleSaveDraft =
    useCallback(
      (questions: unknown) => {
        if (!Array.isArray(questions)) {
          toast.error(
            "Invalid assessment questions.",
          );
          return;
        }

        const normalized =
          questions.filter(
            (
              question,
            ): question is GeneratedQuestion =>
              typeof question ===
                "object" &&
              question !== null &&
              "text" in question &&
              typeof (
                question as {
                  text?: unknown;
                }
              ).text === "string",
          );

        if (!normalized.length) {
          toast.error(
            "No valid questions were generated.",
          );
          return;
        }

        setGeneratedQuestions(
          normalized,
        );

        toast.success(
          `${normalized.length} question${
            normalized.length === 1
              ? ""
              : "s"
          } ready for publishing.`,
        );
      },
      [],
    );

  return (
    <div
      className={cn(
        "grid min-h-0 flex-1 grid-cols-1 gap-5",
        "lg:grid-cols-[19rem_minmax(0,1fr)_19rem]",
        className,
      )}
    >
      {/* LEFT — NOVA */}
      <div className="card-3d flex flex-col items-center gap-5 rounded-2xl p-5">

        <div className="w-full max-w-[14rem]">
          <Companion
            expression={status.expression}
            talking={
              status.state ===
              "speaking"
            }
            pulse={status.pulse}
          />
        </div>

        <div className="text-center">
          <h1 className="font-display text-2xl tracking-[0.2em] text-gradient">
            NOVA
          </h1>

          <p className="mt-1 text-[10px] tracking-[0.22em] text-muted-foreground uppercase sm:text-xs">
            Vision Mentor X · AI
            interview companion
          </p>
        </div>

        <span className="inline-flex items-center gap-2 rounded-full border border-cyber/30 bg-surface/60 px-3 py-1 text-[10px] tracking-[0.22em] uppercase backdrop-blur-md">
          <span className="size-1.5 rounded-full bg-cyber" />

          <span className="text-cyber">
            {stateLabel(
              status.state,
            )}
          </span>

          <span className="text-muted-foreground">
            ·{" "}
            {expressionLabel(
              status.expression,
            )}
          </span>
        </span>

        {novaVoices.length > 0 && (
          <div className="w-full space-y-1">
            <label
              htmlFor="nova-console-voice-select"
              className="flex items-center gap-1.5 text-[9px] tracking-[0.18em] text-muted-foreground uppercase"
            >
              <Mic2 className="size-3" />
              Nova's voice
            </label>

            <select
              id="nova-console-voice-select"
              value={
                activeVoice?.voiceURI ??
                ""
              }
              onChange={(event) =>
                setVoice(
                  event.target.value,
                )
              }
              className="w-full rounded-lg border border-cyber/25 bg-surface/60 px-2.5 py-1.5 text-[11px] text-foreground backdrop-blur-md focus:border-cyber focus:outline-none"
            >
              {novaVoices.map(
                (voice) => (
                  <option
                    key={
                      voice.voiceURI
                    }
                    value={
                      voice.voiceURI
                    }
                  >
                    {voiceLabel(
                      voice,
                    )}
                  </option>
                ),
              )}
            </select>

            {fellBack && (
              <p className="text-[10px] text-muted-foreground">
                Preferred voice
                unavailable —
                using{" "}
                {activeVoice
                  ? voiceLabel(
                      activeVoice,
                    )
                  : "the browser default"}.
              </p>
            )}
          </div>
        )}

        <div className="grid w-full grid-cols-2 gap-2">
          <div className="chip-3d flex flex-col items-center gap-1 rounded-xl p-2.5">
            <Radio className="size-4 text-cyber" />

            <span className="text-[10px] tracking-widest text-muted-foreground uppercase">
              Voice
            </span>

            <span className="text-[10px] text-muted-foreground">
              {senses.micOn
                ? visionStatus.audio.text
                : "OFFLINE"}
            </span>
          </div>

          <div className="chip-3d flex flex-col items-center gap-1 rounded-xl p-2.5">
            <Camera className="size-4 text-cyber" />

            <span className="text-[10px] tracking-widest text-muted-foreground uppercase">
              Vision
            </span>

            <span className="text-center text-[10px] leading-tight text-muted-foreground">
              {senses.cameraOn
                ? visionStatus.posture.text
                : "OFFLINE"}
            </span>
          </div>
        </div>

        <button
          type="button"
          onClick={() =>
            sensing
              ? senses.disable()
              : void senses.enable()
          }
          className={cn(
            "inline-flex items-center gap-2 rounded-full px-4 py-2 text-xs font-medium transition-all",
            sensing
              ? "chip-3d text-muted-foreground"
              : "btn-3d text-primary-foreground",
          )}
        >
          <Camera className="size-3.5" />

          {sensing
            ? "Stop seeing & hearing me"
            : "Let Nova see & hear me"}
        </button>

        {senses.error && (
          <p className="text-[11px] text-destructive">
            {senses.error}
          </p>
        )}

        <NovaDemoPanel />
      </div>

      {/* CENTRE — CONVERSATION */}
      <div className="card-3d flex min-h-[28rem] flex-col rounded-2xl p-5 lg:min-h-0">
        <NovaConversationPanel
          ref={conversationRef}
          onStatusChange={setStatus}
          onListeningChange={
            setListening
          }
          onMicSupportedChange={
            setMicSupported
          }
          onCompanyCommand={
            handleCompanyCommand
          }
        />
      </div>

      {/* RIGHT — HIRING COPILOT */}
      <div className="flex min-h-0 flex-col gap-5">

        <NovaVoiceControl
          state={status.state}
          listening={listening}
          micSupported={
            micSupported
          }
          micLevel={
            senses.micLevel
          }
          onTapToTalk={
            handleTapToTalk
          }
        />

        <div className="card-3d rounded-2xl p-4">
          <CompanyNovaActions
            onAction={
              handleCompanyAction
            }
          />
        </div>

        {showQuestionGenerator && (
          <div className="card-3d rounded-2xl p-4">
            <CompanyQuestionGenerator
              companyUserId={
                companyUserId
              }
              initialConfig={
                questionGeneratorConfig
              }
              onClose={() =>
                setShowQuestionGenerator(
                  false,
                )
              }
              onSaveDraft={
                handleSaveDraft
              }
              onQuestionsGenerated={
                handleSaveDraft
              }
            />

            {generatedQuestions.length >
              0 && (
              <div className="mt-4 rounded-xl border border-cyber/30 bg-cyber/5 p-3">

                <p className="text-xs font-medium text-foreground">
                  {
                    generatedQuestions.length
                  }{" "}
                  questions ready
                </p>

                <p className="mt-1 text-[10px] text-muted-foreground">
                  Say{" "}
                  <span className="text-cyber">
                    "publish it"
                  </span>{" "}
                  to publish this
                  assessment.
                </p>

                <button
                  type="button"
                  disabled={
                    publishing
                  }
                  onClick={() =>
                    void publishGeneratedAssessment()
                  }
                  className="mt-3 w-full rounded-lg bg-cyber px-3 py-2 text-xs font-medium text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-50"
                >
                  {publishing
                    ? "Publishing..."
                    : "Publish Assessment"}
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}