/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as InterviewerRouteRouteImport } from './routes/interviewer/route'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as ACodeRouteImport } from './routes/a.$code'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCompanyGenerateQuestionsRouteImport } from './routes/api/company-generate-questions'
import { Route as ApiSecurityReportRouteImport } from './routes/api/security-report'
import { Route as InterviewerIndexRouteImport } from './routes/interviewer/index'
import { Route as InterviewerDashboardRouteImport } from './routes/interviewer/dashboard'
import { Route as InterviewerInterviewRouteImport } from './routes/interviewer/interview'
import { Route as InterviewerSetupRouteImport } from './routes/interviewer/setup'
import { Route as AuthenticatedCompanyIndexRouteImport } from './routes/_authenticated/company/index'
import { Route as AuthenticatedCompanyNewRouteImport } from './routes/_authenticated/company/new'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardCandidatesRouteImport } from './routes/_authenticated/dashboard/candidates'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedReportIdRouteImport } from './routes/_authenticated/report/$id'
import { Route as ApiDbAssessmentRouteImport } from './routes/api/db/assessment'
import { Route as ApiDbInterviewRouteImport } from './routes/api/db/interview'
import { Route as ApiDbPingRouteImport } from './routes/api/db/ping'
import { Route as ApiDbUserRouteImport } from './routes/api/db/user'
import { Route as ApiDbUserProfileRouteImport } from './routes/api/db/user-profile'
import { Route as ApiNovaPublishAssessmentRouteImport } from './routes/api/nova/publish-assessment'
import { Route as InterviewerReportSessionIdRouteImport } from './routes/interviewer/report.$sessionId'
import { Route as AuthenticatedCompanyAssessmentIdRouteImport } from './routes/_authenticated/company/assessment/$id'
import { Route as AuthenticatedDashboardAssessmentsIndexRouteImport } from './routes/_authenticated/dashboard/assessments/index'
import { Route as AuthenticatedDashboardAssessmentsCodeRouteImport } from './routes/_authenticated/dashboard/assessments/$code'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewerRouteRoute = InterviewerRouteRouteImport.update({
  id: '/interviewer',
  path: '/interviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ACodeRoute = ACodeRouteImport.update({
  id: '/a/$code',
  path: '/a/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanyGenerateQuestionsRoute =
  ApiCompanyGenerateQuestionsRouteImport.update({
    id: '/api/company-generate-questions',
    path: '/api/company-generate-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSecurityReportRoute = ApiSecurityReportRouteImport.update({
  id: '/api/security-report',
  path: '/api/security-report',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewerIndexRoute = InterviewerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterviewerRouteRoute,
} as any)
const InterviewerDashboardRoute = InterviewerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InterviewerRouteRoute,
} as any)
const InterviewerInterviewRoute = InterviewerInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => InterviewerRouteRoute,
} as any)
const InterviewerSetupRoute = InterviewerSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => InterviewerRouteRoute,
} as any)
const AuthenticatedCompanyIndexRoute =
  AuthenticatedCompanyIndexRouteImport.update({
    id: '/company/',
    path: '/company/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyNewRoute = AuthenticatedCompanyNewRouteImport.update({
  id: '/company/new',
  path: '/company/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCandidatesRoute =
  AuthenticatedDashboardCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedReportIdRoute = AuthenticatedReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDbAssessmentRoute = ApiDbAssessmentRouteImport.update({
  id: '/api/db/assessment',
  path: '/api/db/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbInterviewRoute = ApiDbInterviewRouteImport.update({
  id: '/api/db/interview',
  path: '/api/db/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbPingRoute = ApiDbPingRouteImport.update({
  id: '/api/db/ping',
  path: '/api/db/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbUserRoute = ApiDbUserRouteImport.update({
  id: '/api/db/user',
  path: '/api/db/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbUserProfileRoute = ApiDbUserProfileRouteImport.update({
  id: '/api/db/user-profile',
  path: '/api/db/user-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNovaPublishAssessmentRoute =
  ApiNovaPublishAssessmentRouteImport.update({
    id: '/api/nova/publish-assessment',
    path: '/api/nova/publish-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const InterviewerReportSessionIdRoute =
  InterviewerReportSessionIdRouteImport.update({
    id: '/report/$sessionId',
    path: '/report/$sessionId',
    getParentRoute: () => InterviewerRouteRoute,
  } as any)
const AuthenticatedCompanyAssessmentIdRoute =
  AuthenticatedCompanyAssessmentIdRouteImport.update({
    id: '/company/assessment/$id',
    path: '/company/assessment/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAssessmentsIndexRoute =
  AuthenticatedDashboardAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAssessmentsCodeRoute =
  AuthenticatedDashboardAssessmentsCodeRouteImport.update({
    id: '/assessments/$code',
    path: '/assessments/$code',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/interviewer': typeof InterviewerRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof ChatbotRoute
  '/demo': typeof DemoRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/a/$code': typeof ACodeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/company-generate-questions': typeof ApiCompanyGenerateQuestionsRoute
  '/api/security-report': typeof ApiSecurityReportRoute
  '/interviewer/dashboard': typeof InterviewerDashboardRoute
  '/interviewer/interview': typeof InterviewerInterviewRoute
  '/interviewer/setup': typeof InterviewerSetupRoute
  '/interviewer/': typeof InterviewerIndexRoute
  '/company/new': typeof AuthenticatedCompanyNewRoute
  '/dashboard/candidates': typeof AuthenticatedDashboardCandidatesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/api/db/assessment': typeof ApiDbAssessmentRoute
  '/api/db/interview': typeof ApiDbInterviewRoute
  '/api/db/ping': typeof ApiDbPingRoute
  '/api/db/user': typeof ApiDbUserRoute
  '/api/db/user-profile': typeof ApiDbUserProfileRoute
  '/api/nova/publish-assessment': typeof ApiNovaPublishAssessmentRoute
  '/interviewer/report/$sessionId': typeof InterviewerReportSessionIdRoute
  '/company/': typeof AuthenticatedCompanyIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/company/assessment/$id': typeof AuthenticatedCompanyAssessmentIdRoute
  '/dashboard/assessments/$code': typeof AuthenticatedDashboardAssessmentsCodeRoute
  '/dashboard/assessments/': typeof AuthenticatedDashboardAssessmentsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof ChatbotRoute
  '/demo': typeof DemoRoute
  '/welcome': typeof WelcomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/a/$code': typeof ACodeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/company-generate-questions': typeof ApiCompanyGenerateQuestionsRoute
  '/api/security-report': typeof ApiSecurityReportRoute
  '/interviewer/dashboard': typeof InterviewerDashboardRoute
  '/interviewer/interview': typeof InterviewerInterviewRoute
  '/interviewer/setup': typeof InterviewerSetupRoute
  '/': typeof AuthenticatedIndexRoute
  '/interviewer': typeof InterviewerIndexRoute
  '/company/new': typeof AuthenticatedCompanyNewRoute
  '/dashboard/candidates': typeof AuthenticatedDashboardCandidatesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/api/db/assessment': typeof ApiDbAssessmentRoute
  '/api/db/interview': typeof ApiDbInterviewRoute
  '/api/db/ping': typeof ApiDbPingRoute
  '/api/db/user': typeof ApiDbUserRoute
  '/api/db/user-profile': typeof ApiDbUserProfileRoute
  '/api/nova/publish-assessment': typeof ApiNovaPublishAssessmentRoute
  '/interviewer/report/$sessionId': typeof InterviewerReportSessionIdRoute
  '/company': typeof AuthenticatedCompanyIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/company/assessment/$id': typeof AuthenticatedCompanyAssessmentIdRoute
  '/dashboard/assessments/$code': typeof AuthenticatedDashboardAssessmentsCodeRoute
  '/dashboard/assessments': typeof AuthenticatedDashboardAssessmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/interviewer': typeof InterviewerRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof ChatbotRoute
  '/demo': typeof DemoRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/a/$code': typeof ACodeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/company-generate-questions': typeof ApiCompanyGenerateQuestionsRoute
  '/api/security-report': typeof ApiSecurityReportRoute
  '/interviewer/dashboard': typeof InterviewerDashboardRoute
  '/interviewer/interview': typeof InterviewerInterviewRoute
  '/interviewer/setup': typeof InterviewerSetupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/interviewer/': typeof InterviewerIndexRoute
  '/_authenticated/company/new': typeof AuthenticatedCompanyNewRoute
  '/_authenticated/dashboard/candidates': typeof AuthenticatedDashboardCandidatesRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/report/$id': typeof AuthenticatedReportIdRoute
  '/api/db/assessment': typeof ApiDbAssessmentRoute
  '/api/db/interview': typeof ApiDbInterviewRoute
  '/api/db/ping': typeof ApiDbPingRoute
  '/api/db/user': typeof ApiDbUserRoute
  '/api/db/user-profile': typeof ApiDbUserProfileRoute
  '/api/nova/publish-assessment': typeof ApiNovaPublishAssessmentRoute
  '/interviewer/report/$sessionId': typeof InterviewerReportSessionIdRoute
  '/_authenticated/company/': typeof AuthenticatedCompanyIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/company/assessment/$id': typeof AuthenticatedCompanyAssessmentIdRoute
  '/_authenticated/dashboard/assessments/$code': typeof AuthenticatedDashboardAssessmentsCodeRoute
  '/_authenticated/dashboard/assessments/': typeof AuthenticatedDashboardAssessmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interviewer'
    | '/about'
    | '/auth'
    | '/chatbot'
    | '/demo'
    | '/welcome'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/a/$code'
    | '/api/chat'
    | '/api/company-generate-questions'
    | '/api/security-report'
    | '/interviewer/dashboard'
    | '/interviewer/interview'
    | '/interviewer/setup'
    | '/interviewer/'
    | '/company/new'
    | '/dashboard/candidates'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/report/$id'
    | '/api/db/assessment'
    | '/api/db/interview'
    | '/api/db/ping'
    | '/api/db/user'
    | '/api/db/user-profile'
    | '/api/nova/publish-assessment'
    | '/interviewer/report/$sessionId'
    | '/company/'
    | '/dashboard/'
    | '/company/assessment/$id'
    | '/dashboard/assessments/$code'
    | '/dashboard/assessments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/auth'
    | '/chatbot'
    | '/demo'
    | '/welcome'
    | '/profile'
    | '/reports'
    | '/a/$code'
    | '/api/chat'
    | '/api/company-generate-questions'
    | '/api/security-report'
    | '/interviewer/dashboard'
    | '/interviewer/interview'
    | '/interviewer/setup'
    | '/'
    | '/interviewer'
    | '/company/new'
    | '/dashboard/candidates'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/report/$id'
    | '/api/db/assessment'
    | '/api/db/interview'
    | '/api/db/ping'
    | '/api/db/user'
    | '/api/db/user-profile'
    | '/api/nova/publish-assessment'
    | '/interviewer/report/$sessionId'
    | '/company'
    | '/dashboard'
    | '/company/assessment/$id'
    | '/dashboard/assessments/$code'
    | '/dashboard/assessments'
  id:
    | '__root__'
    | '/_authenticated'
    | '/interviewer'
    | '/about'
    | '/auth'
    | '/chatbot'
    | '/demo'
    | '/welcome'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/a/$code'
    | '/api/chat'
    | '/api/company-generate-questions'
    | '/api/security-report'
    | '/interviewer/dashboard'
    | '/interviewer/interview'
    | '/interviewer/setup'
    | '/_authenticated/'
    | '/interviewer/'
    | '/_authenticated/company/new'
    | '/_authenticated/dashboard/candidates'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/report/$id'
    | '/api/db/assessment'
    | '/api/db/interview'
    | '/api/db/ping'
    | '/api/db/user'
    | '/api/db/user-profile'
    | '/api/nova/publish-assessment'
    | '/interviewer/report/$sessionId'
    | '/_authenticated/company/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/company/assessment/$id'
    | '/_authenticated/dashboard/assessments/$code'
    | '/_authenticated/dashboard/assessments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  InterviewerRouteRoute: typeof InterviewerRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ChatbotRoute: typeof ChatbotRoute
  DemoRoute: typeof DemoRoute
  WelcomeRoute: typeof WelcomeRoute
  ACodeRoute: typeof ACodeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCompanyGenerateQuestionsRoute: typeof ApiCompanyGenerateQuestionsRoute
  ApiSecurityReportRoute: typeof ApiSecurityReportRoute
  ApiDbAssessmentRoute: typeof ApiDbAssessmentRoute
  ApiDbInterviewRoute: typeof ApiDbInterviewRoute
  ApiDbPingRoute: typeof ApiDbPingRoute
  ApiDbUserRoute: typeof ApiDbUserRoute
  ApiDbUserProfileRoute: typeof ApiDbUserProfileRoute
  ApiNovaPublishAssessmentRoute: typeof ApiNovaPublishAssessmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviewer': {
      id: '/interviewer'
      path: '/interviewer'
      fullPath: '/interviewer'
      preLoaderRoute: typeof InterviewerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/a/$code': {
      id: '/a/$code'
      path: '/a/$code'
      fullPath: '/a/$code'
      preLoaderRoute: typeof ACodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company-generate-questions': {
      id: '/api/company-generate-questions'
      path: '/api/company-generate-questions'
      fullPath: '/api/company-generate-questions'
      preLoaderRoute: typeof ApiCompanyGenerateQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security-report': {
      id: '/api/security-report'
      path: '/api/security-report'
      fullPath: '/api/security-report'
      preLoaderRoute: typeof ApiSecurityReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviewer/': {
      id: '/interviewer/'
      path: '/'
      fullPath: '/interviewer/'
      preLoaderRoute: typeof InterviewerIndexRouteImport
      parentRoute: typeof InterviewerRouteRoute
    }
    '/interviewer/dashboard': {
      id: '/interviewer/dashboard'
      path: '/dashboard'
      fullPath: '/interviewer/dashboard'
      preLoaderRoute: typeof InterviewerDashboardRouteImport
      parentRoute: typeof InterviewerRouteRoute
    }
    '/interviewer/interview': {
      id: '/interviewer/interview'
      path: '/interview'
      fullPath: '/interviewer/interview'
      preLoaderRoute: typeof InterviewerInterviewRouteImport
      parentRoute: typeof InterviewerRouteRoute
    }
    '/interviewer/setup': {
      id: '/interviewer/setup'
      path: '/setup'
      fullPath: '/interviewer/setup'
      preLoaderRoute: typeof InterviewerSetupRouteImport
      parentRoute: typeof InterviewerRouteRoute
    }
    '/_authenticated/company/': {
      id: '/_authenticated/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof AuthenticatedCompanyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company/new': {
      id: '/_authenticated/company/new'
      path: '/company/new'
      fullPath: '/company/new'
      preLoaderRoute: typeof AuthenticatedCompanyNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/candidates': {
      id: '/_authenticated/dashboard/candidates'
      path: '/candidates'
      fullPath: '/dashboard/candidates'
      preLoaderRoute: typeof AuthenticatedDashboardCandidatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/report/$id': {
      id: '/_authenticated/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AuthenticatedReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/db/assessment': {
      id: '/api/db/assessment'
      path: '/api/db/assessment'
      fullPath: '/api/db/assessment'
      preLoaderRoute: typeof ApiDbAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/interview': {
      id: '/api/db/interview'
      path: '/api/db/interview'
      fullPath: '/api/db/interview'
      preLoaderRoute: typeof ApiDbInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/ping': {
      id: '/api/db/ping'
      path: '/api/db/ping'
      fullPath: '/api/db/ping'
      preLoaderRoute: typeof ApiDbPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/user': {
      id: '/api/db/user'
      path: '/api/db/user'
      fullPath: '/api/db/user'
      preLoaderRoute: typeof ApiDbUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/user-profile': {
      id: '/api/db/user-profile'
      path: '/api/db/user-profile'
      fullPath: '/api/db/user-profile'
      preLoaderRoute: typeof ApiDbUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nova/publish-assessment': {
      id: '/api/nova/publish-assessment'
      path: '/api/nova/publish-assessment'
      fullPath: '/api/nova/publish-assessment'
      preLoaderRoute: typeof ApiNovaPublishAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviewer/report/$sessionId': {
      id: '/interviewer/report/$sessionId'
      path: '/report/$sessionId'
      fullPath: '/interviewer/report/$sessionId'
      preLoaderRoute: typeof InterviewerReportSessionIdRouteImport
      parentRoute: typeof InterviewerRouteRoute
    }
    '/_authenticated/company/assessment/$id': {
      id: '/_authenticated/company/assessment/$id'
      path: '/company/assessment/$id'
      fullPath: '/company/assessment/$id'
      preLoaderRoute: typeof AuthenticatedCompanyAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/assessments/': {
      id: '/_authenticated/dashboard/assessments/'
      path: '/assessments'
      fullPath: '/dashboard/assessments/'
      preLoaderRoute: typeof AuthenticatedDashboardAssessmentsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/assessments/$code': {
      id: '/_authenticated/dashboard/assessments/$code'
      path: '/assessments/$code'
      fullPath: '/dashboard/assessments/$code'
      preLoaderRoute: typeof AuthenticatedDashboardAssessmentsCodeRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardCandidatesRoute: typeof AuthenticatedDashboardCandidatesRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAssessmentsCodeRoute: typeof AuthenticatedDashboardAssessmentsCodeRoute
  AuthenticatedDashboardAssessmentsIndexRoute: typeof AuthenticatedDashboardAssessmentsIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardCandidatesRoute:
      AuthenticatedDashboardCandidatesRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAssessmentsCodeRoute:
      AuthenticatedDashboardAssessmentsCodeRoute,
    AuthenticatedDashboardAssessmentsIndexRoute:
      AuthenticatedDashboardAssessmentsIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCompanyNewRoute: typeof AuthenticatedCompanyNewRoute
  AuthenticatedReportIdRoute: typeof AuthenticatedReportIdRoute
  AuthenticatedCompanyIndexRoute: typeof AuthenticatedCompanyIndexRoute
  AuthenticatedCompanyAssessmentIdRoute: typeof AuthenticatedCompanyAssessmentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCompanyNewRoute: AuthenticatedCompanyNewRoute,
  AuthenticatedReportIdRoute: AuthenticatedReportIdRoute,
  AuthenticatedCompanyIndexRoute: AuthenticatedCompanyIndexRoute,
  AuthenticatedCompanyAssessmentIdRoute: AuthenticatedCompanyAssessmentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface InterviewerRouteRouteChildren {
  InterviewerDashboardRoute: typeof InterviewerDashboardRoute
  InterviewerInterviewRoute: typeof InterviewerInterviewRoute
  InterviewerSetupRoute: typeof InterviewerSetupRoute
  InterviewerIndexRoute: typeof InterviewerIndexRoute
  InterviewerReportSessionIdRoute: typeof InterviewerReportSessionIdRoute
}

const InterviewerRouteRouteChildren: InterviewerRouteRouteChildren = {
  InterviewerDashboardRoute: InterviewerDashboardRoute,
  InterviewerInterviewRoute: InterviewerInterviewRoute,
  InterviewerSetupRoute: InterviewerSetupRoute,
  InterviewerIndexRoute: InterviewerIndexRoute,
  InterviewerReportSessionIdRoute: InterviewerReportSessionIdRoute,
}

const InterviewerRouteRouteWithChildren =
  InterviewerRouteRoute._addFileChildren(InterviewerRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  InterviewerRouteRoute: InterviewerRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ChatbotRoute: ChatbotRoute,
  DemoRoute: DemoRoute,
  WelcomeRoute: WelcomeRoute,
  ACodeRoute: ACodeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCompanyGenerateQuestionsRoute: ApiCompanyGenerateQuestionsRoute,
  ApiSecurityReportRoute: ApiSecurityReportRoute,
  ApiDbAssessmentRoute: ApiDbAssessmentRoute,
  ApiDbInterviewRoute: ApiDbInterviewRoute,
  ApiDbPingRoute: ApiDbPingRoute,
  ApiDbUserRoute: ApiDbUserRoute,
  ApiDbUserProfileRoute: ApiDbUserProfileRoute,
  ApiNovaPublishAssessmentRoute: ApiNovaPublishAssessmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
